sudo: required
language: node_js
node_js:
  - '6'
services:
  - docker
script:
  - 'echo "TODO: add integration tests"'

before_script:
  - npm i @npm-wharf/shipwright@latest -g

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - shipwright build image --repo=npmjs --name=npm-npm2es
